[package]
name = "fuse-test"
version = "0.1.0"
authors = ["White-Green"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuse = "0.3.1"
env_logger = "0.8.1"
libc = "0.2.80"
time = "0.1"
log = "0.4.11"